apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  labels:
    name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    scrape_configs:
      - job_name: 'auth-api'
        static_configs:
          - targets: ['auth-api-monitoring.default.svc.cluster.local:80']