apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasource
  labels:
    app: grafana
data:
  prometheus-datasource.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://192.168.49.2:30090
        isDefault: true
