apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: auth-api-monitor
  labels:
    release: prometheus-stack
spec:
  selector:
    matchLabels:
      app: auth-api
  endpoints:
    - port: metrics
      interval: 15s
      path: /metrics
  namespaceSelector:
    matchNames:
      - default
