apiVersion: v1
kind: Service
metadata:
  name: auth-api-monitoring
  labels:
    app: auth-api
spec:
  type: NodePort
  selector:
    app: auth-api
  ports:
    - name: metrics
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30091  