apiVersion: apps/v1
kind: Deployment
metadata:
  name: consulta-api
  labels:
    app: consulta-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consulta-api
  template:
    metadata:
      labels:
        app: consulta-api
    spec:
      containers:
        - name: consulta-api
          image: docker.io/mpavani/hackatonfiapnett6-consulta-api:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"