apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: docker.io/mpavani/hackatonfiapnett6-gateway:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - name: config-volume
              mountPath: /app/ocelot.json
              subPath: ocelot.json
      volumes:
        - name: config-volume
          configMap:
            name: gateway-config
