apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-config
data:
  ocelot.json: |
    {
      "Routes": [
        {
          "DownstreamPathTemplate": "/api/agenda/{**catchAll}",
          "DownstreamScheme": "http",
          "DownstreamHostAndPorts": [
            { "Host": "agenda-api", "Port": 80 }
          ],
          "UpstreamPathTemplate": "/agenda/{**catchAll}",
          "UpstreamHttpMethod": [ "GET", "POST", "PUT", "DELETE" ],
          "AuthenticationOptions": {
            "AuthenticationProviderKey": "Bearer",
            "AllowedScopes": []
          },
          "RateLimitOptions": {
            "ClientWhitelist": [],
            "EnableRateLimiting": true,
            "Period": "1m",
            "Limit": 20
          }
        },
        {
          "DownstreamPathTemplate": "/api/auth/login",
          "DownstreamScheme": "http",
          "DownstreamHostAndPorts": [
            { "Host": "auth-api", "Port": 80 }
          ],
          "UpstreamPathTemplate": "/api/auth/login",
          "UpstreamHttpMethod": [ "POST" ]
        },
        {
          "DownstreamPathTemplate": "/api/cadastro/{**catchAll}",
          "DownstreamScheme": "http",
          "DownstreamHostAndPorts": [
            { "Host": "cadastro-api", "Port": 80 }
          ],
          "UpstreamPathTemplate": "/cadastro/{**catchAll}",
          "UpstreamHttpMethod": [ "GET", "POST", "PUT", "DELETE" ],
          "AuthenticationOptions": {
            "AuthenticationProviderKey": "Bearer",
            "AllowedScopes": []
          },
          "RateLimitOptions": {
            "EnableRateLimiting": true,
            "Period": "1m",
            "Limit": 20
          }
        },
        {
          "DownstreamPathTemplate": "/api/consulta/{**catchAll}",
          "DownstreamScheme": "http",
          "DownstreamHostAndPorts": [
            { "Host": "consulta-api", "Port": 80 }
          ],
          "UpstreamPathTemplate": "/consulta/{**catchAll}",
          "UpstreamHttpMethod": [ "GET", "POST", "PUT", "DELETE" ],
          "AuthenticationOptions": {
            "AuthenticationProviderKey": "Bearer",
            "AllowedScopes": []
          },
          "RateLimitOptions": {
            "EnableRateLimiting": true,
            "Period": "1m",
            "Limit": 20
          }
        }
      ],
      "GlobalConfiguration": {
        "BaseUrl": "http://localhost:80",
        "RateLimitOptions": {
          "QuotaExceededMessage": "Você excedeu o limite de requisições.",
          "HttpStatusCode": 429,
          "EnableRateLimiting": true
        }
      }
    }
