apiVersion: apps/v1
kind: Deployment
metadata:
  name: agenda-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: agenda-api
  template:
    metadata:
      labels:
        app: agenda-api
    spec:
      containers:
        - name: agenda-api
          image: docker.io/mpavani/hackatonfiapnett6-agenda-api:latest
          ports:
            - containerPort: 8080
