name: Build, Push and Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: self-hosted
    strategy:
      matrix:
        service: [agenda, auth, cadastro, consulta]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Set Docker paths
      id: set-paths
      run: |
        SERVICE_NAME=${{ matrix.service }}
        SERVICE_CAPITALIZED="$(tr '[:lower:]' '[:upper:]' <<< ${SERVICE_NAME:0:1})${SERVICE_NAME:1}"
        DOCKERFILE="src/Services/${SERVICE_CAPITALIZED}/API/Dockerfile"
        CONTEXT="src/Services/${SERVICE_CAPITALIZED}/API"
        echo "DOCKERFILE=$DOCKERFILE" >> $GITHUB_ENV
        echo "CONTEXT=$CONTEXT" >> $GITHUB_ENV

    - name: Build and push Docker image
      run: |
        docker buildx build \
          --file $DOCKERFILE \
          --tag ${{ secrets.DOCKER_USERNAME }}/hackatonfiapnett6-${{ matrix.service }}-api:latest \
          --push \
          $CONTEXT

    - name: Deploy to Minikube
      run: |
        kubectl rollout restart deployment ${{ matrix.service }}-api
