
name: Deploy to Minikube

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted

    strategy:
      matrix:
        service: [agenda-api, auth-api, cadastro-api, consulta-api, gateway]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          tags: docker.io/${{ secrets.DOCKER_USERNAME }}/hackatonfiapnett6-${{ matrix.service }}:latest
          build-args: |
            PROJECT=${{ matrix.service }}

      - name: Deploy to Minikube
        run: |
          kubectl apply -f ./k8s/${{ matrix.service }}/deployment.yaml
          kubectl apply -f ./k8s/${{ matrix.service }}/service.yaml
