name: Build, Push and Deploy to Kubernetes

on:
  push:
    branches:
      - main

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - name: agenda-api
            path: HackatonFiapNETT6.AgendaMedica.Services.Agenda.API
          - name: auth-api
            path: HackatonFiapNETT6.AgendaMedica.Services.Auth.API
          - name: cadastro-api
            path: HackatonFiapNETT6.AgendaMedica.Services.Cadastro.API
          - name: consulta-api
            path: HackatonFiapNETT6.AgendaMedica.Services.Consulta.API

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and push Docker image
        run: |
          docker build -t docker.io/${{ secrets.DOCKER_USERNAME }}/hackatonfiapnett6-${{ matrix.name }}:latest \
            -f ${{ matrix.path }}/Dockerfile ${{ matrix.path }}
          docker push docker.io/${{ secrets.DOCKER_USERNAME }}/hackatonfiapnett6-${{ matrix.name }}:latest

      - name: Diagnóstico do kubeconfig
        env:
          KUBECONFIG: .kube/config
        run: |
          echo ">> Verificando acesso ao cluster Kubernetes"
          echo "Arquivo em uso: $KUBECONFIG"
          cat $KUBECONFIG
          kubectl config get-contexts
          kubectl config current-context
          kubectl cluster-info

      - name: Apply Kubernetes manifests
        env:
          KUBECONFIG: .kube/config
        run: |
          kubectl apply --validate=false -f k8s/${{ matrix.name }}-deployment.yaml
          kubectl apply --validate=false -f k8s/${{ matrix.name }}-service.yaml